@ApiHost = http://localhost:5294
#@ApiHost = https://localhost:7026

GET {{ApiHost}}/api/districts/1
Accept: application/json

###

GET {{ApiHost}}/api/districts
Accept: application/json

###

GET {{ApiHost}}/api/test/database-connection
Accept: application/json

###