<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyName>Districts.Wpf</AssemblyName>
        <RootNamespace>Districts.Wpf</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    </ItemGroup>

</Project>
